import turtle as t
def rhombus(x, y, a):
    t.fillcolor('green')
    t.begin_fill()
    t.color('green')
    t.up()
    t.setposition(x, y)
    t.down()
    t.forward(a)
    t.right(135)
    t.forward(a)
    t.right(45)
    t.forward(a)
    t.right(135)
    t.forward(a)
    t.right(45)
    t.end_fill()
def rectangle(x, y, a, b):
    t.fillcolor('pink')
    t.begin_fill()
    t.color('pink')
    t.up()
    t.setposition(x, y)
    t.down()
    t.forward(a)
    t.right(90)
    t.forward(b)
    t.right(90)
    t.forward(a)
    t.right(90)
    t.forward(b)
    t.right(90)
    t.end_fill()
def star(x, y, a):
    t.fillcolor('purple')
    t.begin_fill()
    t.color('purple')
    t.up()
    t.setposition(x, y)
    t.down()
    for i in range (5):
        t.forward(a)
        t.left(72)
        t.forward(a)
        t.right(144)
    t.end_fill()
def square(x,y,a):
    t.fillcolor('red')
    t.begin_fill()
    t.color('red')
    t.up()
    t.setposition(x,y)
    t.down()
    for i in range(4):
        t.forward(a)
        t.left(90)
    t.end_fill()
def triangle(x,y,a,b):
    t.fillcolor('yellow')
    t.begin_fill()
    t.color('yellow')
    t.up()
    t.setposition(x,y)
    t.down()
    t.forward(a)
    t.right(90)
    t.forward(b)
    t.right(45)
    t.forward(b)
    t.right(45)
    t.end_fill()
def round(x, y, r):
    t.fillcolor('red')
    t.begin_fill()
    t.color('red')
    t.up()
    t.setposition(x, y)
    t.down()
    t.circle(r)
    t.end_fill()
def trapeze(x, y, a, b, c):
    t.fillcolor('blue')
    t.begin_fill()
    t.color('blue')
    t.up()
    t.setposition(x, y)
    t.down()
    t.forward(a)
    t.right(60)
    t.forward(b)
    t.right(120)
    t.forward(c)
    t.right(120)
    t.forward(b)
    t.right(60)
    t.end_fill()
