import turtle as t
def rhombus(x, y, a):
    t.fillcolor('green')
    t.begin_fill()
    t.color('green')
    t.up()
    t.setposition(x, y)
    t.down()
    t.forward(a)
    t.right(135)
    t.forward(a)
    t.right(45)
    t.forward(a)
    t.right(135)
    t.forward(a)
    t.right(45)
    t.end_fill()
def rectangle(x, y, a, b):
    t.fillcolor('pink')
    t.begin_fill()
    t.color('pink')
    t.up()
    t.setposition(x, y)
    t.down()
    t.forward(a)
    t.right(90)
    t.forward(b)
    t.right(90)
    t.forward(a)
    t.right(90)
    t.forward(b)
    t.right(90)
    t.end_fill()
